---
- name: Deploy Web Server using Apache
  hosts: web_servers
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: true
      tags: deploy

    - name: Enable Apache
      service:
        name: apache2
        state: started
        enabled: true
      tags: deploy

    - name: Change Apache port to 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        line: "Listen 8080"
        create: yes
      tags: deploy

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
      tags: deploy

    - name: Create custom web page
      copy:
        dest: /var/www/html/index.html
        content: "Hello World from SJSU-{{ inventory_hostname[-1] }}"
      tags: deploy

- name: Un-deploy webserver
  hosts: web_servers
  become: true
  tasks:
  
    - name: Remove Web Page
      file:
        path: /var/www/html/index/html
        state: absent
      tags: undeploy
 
    - name: Stop Apache
      service:
        name: apache2  
        state: stopped
      tags: undeploy

    - name: Disable Apache
      service:
        name: apache2
        enabled: false
      tags: undeploy

    - name: Remove Apache
      apt:
        name: apache2
        state: absent
      tags: undeploy
